# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Make sure that no key combinations are overwritten
stty -ixon

# Load scripts
source ~/.bash/aliases.sh
source ~/.bash/tools.sh
source ~/.bash/completions
source ~/.bash/config
source ~/.bash/prompt
source ~/.bash/utilities/remote_host_utilities.sh

# Load localrc
if [ -f ~/.localrc ]; then
  . ~/.localrc
fi

# Load RVM
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# Homebrew
export PATH="/usr/local/sbin:$PATH"
