# SpaceVim configuration
#
# All SpaceVim option below [option] section
[options]
    colorscheme = "gruvbox"
    background = "dark"
    enable_guicolors = true
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = false
    bootstrap_before = "init#before"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'tools'

[[layers]]
name = 'denite'

# Java
[[layers]]
  name = "lang#java"
